twitter:
    consumer_key:        "2XQPZbKrAUUPPPP0X8KeInvJ1"
    consumer_secret:     "0hLCvX99Or68esqWnwBxhGnTyVa9H5QXYNqJGVORn8kG3Ri5VM"
    access_token:        "109758782-llplQD2XIIvJJBO5nbH7qryASIRTdL7HtX9xsImc"
    access_token_secret: "Sa3jvEPxQKhRNvscXR6CUoA0PKQJXhwiOCMsz7W7ydozx"
search:
    trigger:             "ãˆã³,ã‚¨ãƒ“,æµ·è€,è¦,ğŸ¤"
    picture:             "ç”»åƒ,å†™çœŸ"
    video:               "å‹•ç”»,æ˜ åƒ"
    temperature:         "æ¸©åº¦"
response:
    message:             "ãˆã³ã ã‚ˆ"
    temperature:         "#now\n\næ°—æ¸©:#tempâ„ƒ\næ°´æ¸©:#thermoâ„ƒ\nã‚»ãƒ³ã‚µãƒ¼åŸºæº–æ¸©åº¦:#interâ„ƒ\n"
